changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Testing
      labels:
        - testing
    - title: CI and Build
      labels:
        - ci
        - build
        - chore
    - title: Other Changes
      labels:
        - '*'
