[package]
name = "rb-github"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Review Buddy GitHub provider (GraphQL and REST)."

[dependencies]
rb-core.workspace = true

[lints]
workspace = true
